### ISSUE TITLE
Server Crashes if near a Chunk

### ISSUE THREAD

**Issue by svenjaun** [Team-RAM/RAM#36]
Our server constantly stops if someone is at a specific chunk.

Crash log; 
[crash-2020-03-23_17.09.22-server.txt](https://github.com/Team-RAM/RAM/files/4370565/crash-2020-03-23_17.09.22-server.txt)

We don't have a clue what could cause the problem.

**Comment by svenjaun** [comment]
After i saw the error of "Threads: "ComputerCraft-Coroutine-2" i tried to deinstall the cc-tweaked mod but it doesn't changed anything

**Comment by Darkere** [comment]
This is a watchdog crash. That means there was a lag spike that was determined to take too long and as such the server was stopped. 
This, unfortunately, means the crash log is entirely useless. 

What version of the pack are you on?

**Comment by svenjaun** [comment]
RAM-0.2.7 with NaturesAura on version 23.3

**Comment by Darkere** [comment]
That makes that very difficult to figure out.
[Visualvm](https://visualvm.github.io/) can sample the server to see where it is hanging but it's not a very noob-friendly tool. 
Sample the CPU and create and share a snapshot would be what needed to be done. 

Otherwise... we are looking to release an update today. There is always the potential that it will resolve the problem.
