### ISSUE TITLE
WOOT Causing Server Crash - Happens Occasionally After Dye Crash 

### ISSUE THREAD

**Issue by BadHad** [Team-RAM/RAM#62]
https://s.yoosk.ovh/P3NhE

**Comment by FallenEagle1** [comment]
This should be fixed when the other crash #61 is fixed. Some quality of life tips though. In the future, please give more info as to what is going on with the crash (what the server was doing, what the players are doing, etc). Also, a full crash report is necessary, as this snippet doesn't give all the information needed for tracking down issues. With crash reports, either putting them in spoiler tags, or attaching the log through pastebin or similar is appreciated, as it makes scrolling through reports easier. Going to mark this as a duplicate and close for now, since it is directly related to the dye crash.
